import type { Metadata } from "next";
import Image from "next/image";
import { Blocks, Bolt, Film, FolderKanban, Store } from "lucide-react";
import Link from "next/link";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import React from "react";

export const metadata: Metadata = {
  title: "admin - snowden CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="w-full h-full">{children}</div>;
}
